#!/usr/bin/env bash
set -euo pipefail

CHECK_MODE=false
REPO_ROOT="."
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

while [ "$#" -gt 0 ]; do
  case "$1" in
    --check)
      CHECK_MODE=true
      shift
      ;;
    --)
      shift
      break
      ;;
    -*)
      echo "error: unknown option: $1" >&2
      exit 1
      ;;
    *)
      REPO_ROOT="$1"
      shift
      ;;
  esac
done

REPO_ROOT="$(cd "$REPO_ROOT" && pwd)"

if [[ "$REPO_ROOT" == "$SCRIPT_ROOT" &&
  ! -d "$REPO_ROOT/.ai/shared" &&
  -d "$REPO_ROOT/modules" &&
  -d "$REPO_ROOT/skills" ]]; then
  if [[ "$CHECK_MODE" == true ]]; then
    echo "ai-shared source repo; no generated consumer files to check."
    exit 0
  fi

  echo "error: run this script from a consumer repo, or pass a consumer repo path" >&2
  exit 1
fi

SHARED_ROOT="$REPO_ROOT/.ai/shared"
SHARED_MODULES_DIR="$SHARED_ROOT/modules"
SHARED_SKILLS_DIR="$SHARED_ROOT/skills"
LOCAL_SKILLS_DIR="$REPO_ROOT/.ai/local-skills"
MANIFEST_PATH="$REPO_ROOT/.ai/manifest.json"
SHARED_ROOT_FILES=(".coderabbit.yaml")

TMP_ROOT="$(mktemp -d)"
trap 'rm -rf "$TMP_ROOT"' EXIT

GENERATED_CLAUDE_DIR="$TMP_ROOT/.claude/commands"
GENERATED_AGENTS_DIR="$TMP_ROOT/.agents/skills"
GENERATED_PROMPTS_DIR="$TMP_ROOT/prompts"
GENERATED_PROMPT_REGISTRY="$TMP_ROOT/generated-agent-files.txt"

TARGET_CLAUDE_DIR="$REPO_ROOT/.claude/commands"
TARGET_AGENTS_DIR="$REPO_ROOT/.agents/skills"
TARGET_PROMPT_REGISTRY="$REPO_ROOT/.ai/generated-agent-files.txt"
AGENT_FILES_WRITTEN=false

strip_frontmatter() {
  local source_path="$1"

  awk '
    NR == 1 && $0 == "---" {
      in_frontmatter = 1
      next
    }
    in_frontmatter && $0 == "---" {
      in_frontmatter = 0
      next
    }
    !in_frontmatter {
      if (!started && $0 ~ /^[[:space:]]*$/) {
        next
      }
      started = 1
      print
    }
  ' "$source_path"
}

source_has_frontmatter() {
  local source_path="$1"

  head -n 1 "$source_path" | grep -qx -- "---"
}

derive_description() {
  local source_path="$1"

  strip_frontmatter "$source_path" | awk '
    /^# / && !seen_content {
      next
    }
    /^[[:space:]]*$/ {
      if (collecting) {
        exit
      }
      next
    }
    {
      line = $0
      gsub(/[[:space:]]+/, " ", line)
      if (!collecting) {
        description = line
        collecting = 1
        seen_content = 1
        next
      }
      description = description " " line
    }
    END {
      print description
    }
  '
}

yaml_quote() {
  local value="$1"

  value=${value//\'/\'\'}
  printf "'%s'" "$value"
}

copy_skill_to_claude() {
  local source_path="$1"
  local skill_name="$2"
  local target_dir="$3"

  strip_frontmatter "$source_path" > "$target_dir/$skill_name.md"
}

write_agent_skill() {
  local source_path="$1"
  local skill_name="$2"
  local target_path="$3"
  local description=""

  if source_has_frontmatter "$source_path"; then
    cp "$source_path" "$target_path"
    return
  fi

  description="$(derive_description "$source_path")"

  {
    printf -- '---\n'
    printf 'name: %s\n' "$skill_name"
    printf 'description: %s\n' "$(yaml_quote "$description")"
    printf -- '---\n\n'
    strip_frontmatter "$source_path"
  } > "$target_path"
}

copy_skill_to_agents() {
  local source_dir="$1"
  local entry="$2"
  local skill_name="$3"
  local target_dir="$4"
  local target_skill_dir="$target_dir/$skill_name"

  rm -rf "$target_skill_dir"
  mkdir -p "$target_skill_dir"

  if [ -d "$source_dir/$entry" ]; then
    cp -R "$source_dir/$entry/." "$target_skill_dir/"
    write_agent_skill "$source_dir/$entry/SKILL.md" "$skill_name" "$target_skill_dir/SKILL.md"
    return
  fi

  write_agent_skill "$source_dir/$entry" "$skill_name" "$target_skill_dir/SKILL.md"
}

sync_from_source() {
  local source_dir="$1"
  local claude_dir="$2"
  local agents_dir="$3"

  [ -d "$source_dir" ] || return 0

  find "$source_dir" -mindepth 1 -maxdepth 1 | sort | while read -r entry_path; do
    local entry skill_name source_skill_path
    entry="$(basename "$entry_path")"

    case "$entry" in
      .gitkeep|.DS_Store)
        continue
        ;;
    esac

    if [ -d "$entry_path" ]; then
      source_skill_path="$entry_path/SKILL.md"
      [ -f "$source_skill_path" ] || continue
      skill_name="$entry"
    else
      case "$entry" in
        *.md)
          skill_name="${entry%.md}"
          source_skill_path="$entry_path"
          ;;
        *)
          continue
          ;;
      esac
    fi

    copy_skill_to_claude "$source_skill_path" "$skill_name" "$claude_dir"
    copy_skill_to_agents "$source_dir" "$entry" "$skill_name" "$agents_dir"
  done
}

write_placeholder() {
  local target_dir="$1"

  cat > "$target_dir/.gitignore" <<'EOF'
# Generated by sync-ai-skills.sh.
# Keep this file so the directory exists even when no commands are synced yet.
EOF
}

json_runtime() {
  if command -v node >/dev/null 2>&1; then
    command -v node
    return
  fi

  if command -v bun >/dev/null 2>&1; then
    command -v bun
    return
  fi

  echo "error: node or bun is required to read .ai/manifest.json" >&2
  exit 1
}

manifest_value() {
  local expression="$1"
  local runtime
  runtime="$(json_runtime)"

  "$runtime" -e '
    const fs = require("node:fs");
    const manifest = JSON.parse(fs.readFileSync(process.argv[1], "utf8"));
    const value = Function("manifest", `return (${process.argv[2]});`)(manifest);

    if (Array.isArray(value)) {
      console.log(value.join("\n"));
    } else if (value !== undefined && value !== null) {
      console.log(String(value));
    }
  ' "$MANIFEST_PATH" "$expression"
}

manifest_shared_root_files() {
  local runtime
  runtime="$(json_runtime)"

  "$runtime" -e '
    const fs = require("node:fs");
    const path = require("node:path");

    process.on("uncaughtException", (error) => {
      console.error(`error: ${error.message}`);
      process.exit(1);
    });

    const manifestPath = process.argv[1];
    const sharedRoot = fs.realpathSync(process.argv[2]);
    const manifest = JSON.parse(fs.readFileSync(manifestPath, "utf8"));
    const entries = Object.hasOwn(manifest, "sharedRootFiles")
      ? manifest.sharedRootFiles
      : [];

    if (!Array.isArray(entries)) {
      throw new Error("manifest.sharedRootFiles must be an array of non-empty strings");
    }

    for (const [index, entry] of entries.entries()) {
      const field = `manifest.sharedRootFiles[${index}]`;
      if (typeof entry !== "string" || entry.trim().length === 0) {
        throw new Error(`${field} must be a non-empty string`);
      }
      if (entry.includes("\n") || entry.includes("\r")) {
        throw new Error(`${field} must not contain a line break`);
      }
      if (
        path.isAbsolute(entry) ||
        entry.split(/[\\/]/u).some((segment) => segment === "..")
      ) {
        throw new Error(`${field} must be a repo-relative path without ".."`);
      }

      const sourcePath = path.resolve(sharedRoot, entry);
      const sharedPrefix = `${sharedRoot}${path.sep}`;
      if (!sourcePath.startsWith(sharedPrefix)) {
        throw new Error(`${field} must resolve inside .ai/shared`);
      }

      let realSourcePath;
      let source;
      try {
        realSourcePath = fs.realpathSync(sourcePath);
        source = fs.statSync(realSourcePath);
      } catch {
        throw new Error(`${field} references a missing shared file: ${entry}`);
      }
      if (!realSourcePath.startsWith(sharedPrefix)) {
        throw new Error(`${field} must resolve inside .ai/shared`);
      }
      if (!source.isFile()) {
        throw new Error(`${field} must reference a shared file: ${entry}`);
      }

      console.log(entry);
    }
  ' "$MANIFEST_PATH" "$SHARED_ROOT"
}

write_coderabbit_file() {
  local source_path="$1"
  local target_path="$2"
  local runtime
  runtime="$(json_runtime)"

  "$runtime" -e '
    const fs = require("node:fs");
    process.on("uncaughtException", (error) => {
      console.error(`error: ${error.message}`);
      process.exit(1);
    });

    const sourcePath = process.argv[1];
    const manifestPath = process.argv[2];
    const targetPath = process.argv[3];
    const pathFilterMarker = "    # sync-ai: injected path filters";
    const guidelineMarker = "      # sync-ai: injected code guideline file patterns";

    const manifest = fs.existsSync(manifestPath)
      ? JSON.parse(fs.readFileSync(manifestPath, "utf8"))
      : {};

    const coderabbit = manifest.coderabbit ?? {};

    if (
      coderabbit === null ||
      typeof coderabbit !== "object" ||
      Array.isArray(coderabbit)
    ) {
      throw new Error("manifest.coderabbit must be an object");
    }

    const assertStringArray = (value, name) => {
      if (value === undefined) {
        return [];
      }

      if (!Array.isArray(value) || value.some((item) => typeof item !== "string")) {
        throw new Error(`manifest.coderabbit.${name} must be an array of strings`);
      }

      return value;
    };

    const yamlString = (value) => JSON.stringify(value);

    const injectList = (text, marker, indent, values) => {
      if (values.length === 0) {
        return text;
      }

      if (!text.includes(marker)) {
        throw new Error(`missing CodeRabbit injection marker: ${marker.trim()}`);
      }

      const injected = values.map((value) => `${indent}- ${yamlString(value)}`).join("\n");
      return text.replace(marker, `${injected}\n${marker}`);
    };

    let output = fs.readFileSync(sourcePath, "utf8");
    output = injectList(
      output,
      pathFilterMarker,
      "    ",
      assertStringArray(coderabbit.pathFilters, "pathFilters"),
    );
    output = injectList(
      output,
      guidelineMarker,
      "      ",
      assertStringArray(
        coderabbit.codeGuidelineFilePatterns,
        "codeGuidelineFilePatterns",
      ),
    );

    fs.mkdirSync(require("node:path").dirname(targetPath), { recursive: true });
    fs.writeFileSync(targetPath, output.replace(/\n+$/u, "\n"));
  ' "$source_path" "$MANIFEST_PATH" "$target_path"
}

write_agent_files() {
  [ -f "$MANIFEST_PATH" ] || return 0

  local agents_configured runtime
  agents_configured="$(manifest_value 'manifest.agents ? "true" : "false"')"

  [ "$agents_configured" = "true" ] || return 0

  runtime="$(json_runtime)"
  "$runtime" - "$MANIFEST_PATH" "$REPO_ROOT" "$SHARED_MODULES_DIR" \
    "$GENERATED_PROMPTS_DIR" "$GENERATED_PROMPT_REGISTRY" <<'EOF'
const fs = require("node:fs");
const path = require("node:path");

process.on("uncaughtException", (error) => {
  console.error(`error: ${error.message}`);
  process.exit(1);
});

const [manifestPath, repoRootInput, modulesRootInput, outputRoot, registryPath] =
  process.argv.slice(2);
const manifest = JSON.parse(fs.readFileSync(manifestPath, "utf8"));
const repoRoot = fs.realpathSync(repoRootInput);
const modulesRoot = fs.realpathSync(modulesRootInput);
const agents = manifest.agents;
const generatedMarker =
  "<!-- Generated by .ai/shared/scripts/sync-ai-skills.sh from .ai/manifest.json. -->";

if (agents === null || typeof agents !== "object" || Array.isArray(agents)) {
  throw new Error("manifest.agents must be an object");
}

const validateRelativePath = (value, field) => {
  if (typeof value !== "string" || value.trim().length === 0) {
    throw new Error(`${field} must be a non-empty string`);
  }
  if (value.includes("\n") || value.includes("\r")) {
    throw new Error(`${field} must not contain a line break`);
  }
  if (
    path.isAbsolute(value) ||
    value.split(/[\\/]/u).some((segment) => segment === "..")
  ) {
    throw new Error(`${field} must be a repo-relative path without ".."`);
  }
  return path.posix.normalize(value.replaceAll("\\", "/"));
};

const resolveInside = (root, relativePath, field) => {
  const resolved = path.resolve(root, relativePath);
  const prefix = `${root}${path.sep}`;
  if (!resolved.startsWith(prefix)) {
    throw new Error(`${field} must resolve inside the repository`);
  }
  return resolved;
};

const assertExistingPathInside = (root, targetPath, field) => {
  const realPath = fs.realpathSync(targetPath);
  const prefix = `${root}${path.sep}`;
  if (!realPath.startsWith(prefix)) {
    throw new Error(`${field} must resolve inside its configured root`);
  }
  return realPath;
};

const readModules = (moduleNames, field) => {
  if (!Array.isArray(moduleNames)) {
    throw new Error(`${field} must be an array of non-empty strings`);
  }

  return moduleNames.map((moduleName, index) => {
    const itemField = `${field}[${index}]`;
    const normalizedName = validateRelativePath(moduleName, itemField);
    const modulePath = resolveInside(
      modulesRoot,
      `${normalizedName}.md`,
      itemField,
    );
    if (!fs.existsSync(modulePath) || !fs.statSync(modulePath).isFile()) {
      throw new Error(`${itemField} references a missing module: ${moduleName}`);
    }
    return fs
      .readFileSync(
        assertExistingPathInside(modulesRoot, modulePath, itemField),
        "utf8",
      )
      .replace(/\n+$/u, "");
  });
};

const readLocal = (localPath, field, required) => {
  if (localPath === undefined) {
    return "";
  }

  const normalizedPath = validateRelativePath(localPath, field);
  const sourcePath = resolveInside(repoRoot, normalizedPath, field);
  if (!fs.existsSync(sourcePath)) {
    if (required) {
      throw new Error(
        `${field} references a missing local fragment: ${normalizedPath}`,
      );
    }
    return "";
  }
  if (!fs.statSync(sourcePath).isFile()) {
    throw new Error(`${field} must reference a file`);
  }
  return fs
    .readFileSync(assertExistingPathInside(repoRoot, sourcePath, field), "utf8")
    .replace(/\n+$/u, "");
};

const normalizeTitle = (title, fallback, field) => {
  if (title === undefined) {
    return fallback;
  }
  if (
    typeof title !== "string" ||
    title.trim().length === 0 ||
    title.includes("\n") ||
    title.includes("\r")
  ) {
    throw new Error(`${field} must be a non-empty, single-line string`);
  }
  return title;
};

const scopes = agents.scopes ?? [];
if (!Array.isArray(scopes)) {
  throw new Error("manifest.agents.scopes must be an array");
}

const definitions = [
  {
    path: "",
    title: normalizeTitle(agents.title, "AGENTS.md", "manifest.agents.title"),
    modules: agents.modules ?? [],
    local: agents.local ?? ".ai/local/agents.md",
    localRequired: Object.hasOwn(agents, "local"),
    field: "manifest.agents",
  },
];
const seenScopes = new Set();

for (const [index, scope] of scopes.entries()) {
  const field = `manifest.agents.scopes[${index}]`;
  if (scope === null || typeof scope !== "object" || Array.isArray(scope)) {
    throw new Error(`${field} must be an object`);
  }

  const scopePath = validateRelativePath(scope.path, `${field}.path`);
  if (scopePath === ".") {
    throw new Error(`${field}.path must identify a nested repository directory`);
  }
  if (seenScopes.has(scopePath)) {
    throw new Error(`${field}.path duplicates scope: ${scopePath}`);
  }

  const targetDirectory = resolveInside(repoRoot, scopePath, `${field}.path`);
  if (
    !fs.existsSync(targetDirectory) ||
    !fs.statSync(targetDirectory).isDirectory()
  ) {
    throw new Error(`${field}.path references a missing directory: ${scopePath}`);
  }
  assertExistingPathInside(repoRoot, targetDirectory, `${field}.path`);

  seenScopes.add(scopePath);
  definitions.push({
    path: scopePath,
    title: normalizeTitle(
      scope.title,
      `${scopePath} Development Guidelines`,
      `${field}.title`,
    ),
    modules: scope.modules ?? [],
    local: scope.local,
    localRequired: Object.hasOwn(scope, "local"),
    field,
  });
}

const promptPaths = [];
const writePrompt = (relativePath, contents) => {
  const targetPath = path.join(outputRoot, relativePath);
  fs.mkdirSync(path.dirname(targetPath), { recursive: true });
  fs.writeFileSync(targetPath, contents.replace(/\n*$/u, "\n"));
  promptPaths.push(relativePath);
};

for (const definition of definitions) {
  const updateSources = definition.local
    ? `shared modules or ${definition.local}`
    : "shared modules or the manifest scope";
  const sections = readModules(
    definition.modules,
    `${definition.field}.modules`,
  );
  const local = readLocal(
    definition.local,
    `${definition.field}.local`,
    definition.localRequired,
  );
  if (local.length > 0) {
    sections.push(local);
  }

  const prefix = definition.path ? `${definition.path}/` : "";
  writePrompt(
    `${prefix}AGENTS.md`,
    [
      `# ${definition.title}`,
      "",
      generatedMarker,
      `<!-- Do not edit directly; update ${updateSources}, then run \`bun run sync-ai\`. -->`,
      "",
      sections.join("\n\n"),
    ].join("\n"),
  );

  const claudeContents = definition.path
    ? `${generatedMarker}\n@AGENTS.md\n`
    : [
        "@AGENTS.md",
        "",
        "## Claude Code",
        "",
        "Use the project skills in `.agents/skills/` or `.claude/commands/` when a task",
        "matches one of those workflows.",
        "",
      ].join("\n");
  const geminiContents = definition.path
    ? `${generatedMarker}\n@AGENTS.md\n`
    : [
        "@AGENTS.md",
        "",
        "## Gemini CLI",
        "",
        "Use `AGENTS.md` as the project context.",
        "",
      ].join("\n");
  writePrompt(`${prefix}CLAUDE.md`, claudeContents);
  writePrompt(`${prefix}GEMINI.md`, geminiContents);
}

fs.writeFileSync(registryPath, `${promptPaths.sort().join("\n")}\n`);
EOF

  AGENT_FILES_WRITTEN=true
}

compare_agent_files() {
  local errors=0 prompt_path

  compare_file "$GENERATED_PROMPT_REGISTRY" "$TARGET_PROMPT_REGISTRY" ||
    errors=$((errors + 1))

  while IFS= read -r prompt_path; do
    [ -n "$prompt_path" ] || continue
    compare_file "$GENERATED_PROMPTS_DIR/$prompt_path" "$REPO_ROOT/$prompt_path" ||
      errors=$((errors + 1))
  done < "$GENERATED_PROMPT_REGISTRY"

  return "$errors"
}

install_agent_files() {
  local runtime
  runtime="$(json_runtime)"

  "$runtime" - "$REPO_ROOT" "$GENERATED_PROMPTS_DIR" \
    "$GENERATED_PROMPT_REGISTRY" "$TARGET_PROMPT_REGISTRY" <<'EOF'
const fs = require("node:fs");
const path = require("node:path");

process.on("uncaughtException", (error) => {
  console.error(`error: ${error.message}`);
  process.exit(1);
});

const [repoRootInput, sourceRoot, sourceRegistry, targetRegistry] =
  process.argv.slice(2);
const repoRoot = fs.realpathSync(repoRootInput);
const prefix = `${repoRoot}${path.sep}`;
const generatedMarker =
  "<!-- Generated by .ai/shared/scripts/sync-ai-skills.sh from .ai/manifest.json. -->";

const readRegistry = (registryPath) => {
  if (!fs.existsSync(registryPath)) {
    return [];
  }
  return fs
    .readFileSync(registryPath, "utf8")
    .split("\n")
    .filter(Boolean);
};

const resolvePrompt = (relativePath) => {
  if (
    path.isAbsolute(relativePath) ||
    relativePath.split(/[\\/]/u).some((segment) => segment === "..") ||
    !["AGENTS.md", "CLAUDE.md", "GEMINI.md"].includes(path.basename(relativePath))
  ) {
    throw new Error(`invalid generated prompt path: ${relativePath}`);
  }

  const resolved = path.resolve(repoRoot, relativePath);
  if (!resolved.startsWith(prefix)) {
    throw new Error(`generated prompt path escapes repository: ${relativePath}`);
  }

  const parentPath = path.dirname(resolved);
  if (fs.existsSync(parentPath)) {
    const realParentPath = fs.realpathSync(parentPath);
    if (realParentPath !== repoRoot && !realParentPath.startsWith(prefix)) {
      throw new Error(
        `generated prompt parent escapes repository: ${relativePath}`,
      );
    }
  }
  return resolved;
};

const existingEntry = (targetPath) =>
  fs.lstatSync(targetPath, { throwIfNoEntry: false });

const desired = readRegistry(sourceRegistry);
const desiredSet = new Set(desired);

for (const stalePath of readRegistry(targetRegistry)) {
  if (!desiredSet.has(stalePath)) {
    const targetPath = resolvePrompt(stalePath);
    const existing = existingEntry(targetPath);
    if (existing?.isSymbolicLink()) {
      fs.rmSync(targetPath);
    } else if (existing) {
      if (!existing.isFile()) {
        throw new Error(
          `refusing to remove a non-file prompt entry: ${stalePath}`,
        );
      }
      const contents = fs.readFileSync(targetPath, "utf8");
      if (!contents.includes(generatedMarker)) {
        throw new Error(
          `refusing to remove an unmarked prompt file: ${stalePath}`,
        );
      }
      fs.rmSync(targetPath);
    }
  }
}

for (const relativePath of desired) {
  const targetPath = resolvePrompt(relativePath);
  const sourcePath = path.resolve(sourceRoot, relativePath);
  fs.mkdirSync(path.dirname(targetPath), { recursive: true });
  const existing = existingEntry(targetPath);
  if (existing?.isSymbolicLink()) {
    fs.rmSync(targetPath);
  } else if (existing && !existing.isFile()) {
    throw new Error(
      `refusing to overwrite a non-file prompt entry: ${relativePath}`,
    );
  }
  fs.copyFileSync(sourcePath, targetPath);
}

fs.mkdirSync(path.dirname(targetRegistry), { recursive: true });
fs.copyFileSync(sourceRegistry, targetRegistry);
EOF
}

write_skill_files() {
  mkdir -p "$GENERATED_CLAUDE_DIR" "$GENERATED_AGENTS_DIR"

  sync_from_source "$SHARED_SKILLS_DIR" "$GENERATED_CLAUDE_DIR" "$GENERATED_AGENTS_DIR"
  sync_from_source "$LOCAL_SKILLS_DIR" "$GENERATED_CLAUDE_DIR" "$GENERATED_AGENTS_DIR"

  write_placeholder "$GENERATED_CLAUDE_DIR"
  write_placeholder "$GENERATED_AGENTS_DIR"
}

write_shared_root_files() {
  local file_name source_path

  for file_name in "${SHARED_ROOT_FILES[@]}"; do
    source_path="$SHARED_ROOT/$file_name"

    [ -f "$source_path" ] || continue

    mkdir -p "$(dirname "$TMP_ROOT/$file_name")"
    case "$file_name" in
      .coderabbit.yaml)
        write_coderabbit_file "$source_path" "$TMP_ROOT/$file_name"
        ;;
      *)
        cp "$source_path" "$TMP_ROOT/$file_name"
        ;;
    esac
  done
}

compare_file() {
  local generated_path="$1"
  local target_path="$2"

  if [ ! -f "$target_path" ] || ! cmp -s "$generated_path" "$target_path"; then
    echo "error: $target_path is stale. Run: bun run sync-ai" >&2
    return 1
  fi
}

compare_dir() {
  local generated_path="$1"
  local target_path="$2"

  if [ ! -d "$target_path" ]; then
    echo "error: $target_path is missing. Run: bun run sync-ai" >&2
    return 1
  fi

  if ! diff -qr "$generated_path" "$target_path" >/dev/null; then
    echo "error: $target_path is stale. Run: bun run sync-ai" >&2
    diff -qr "$generated_path" "$target_path" >&2 || true
    return 1
  fi
}

# Consumer repos can opt into additional shared root files (for example the
# shared Rust lint policy: rustfmt.toml, clippy.toml, deny.toml) via
# `.ai/manifest.json` "sharedRootFiles". They are copied verbatim from
# `.ai/shared/` and verified by --check, exactly like .coderabbit.yaml. This is
# opt-in so repos with stricter local configs are never clobbered.
if [ -f "$MANIFEST_PATH" ]; then
  shared_root_files="$(manifest_shared_root_files)" || exit 1
  while IFS= read -r extra_root_file; do
    [ -n "$extra_root_file" ] || continue
    SHARED_ROOT_FILES+=("$extra_root_file")
  done <<< "$shared_root_files"
fi

write_agent_files
write_skill_files
write_shared_root_files

if [ "$CHECK_MODE" = true ]; then
  errors=0
  root_file=""

  if [ "$AGENT_FILES_WRITTEN" = true ]; then
    compare_agent_files || errors=$((errors + 1))
  fi

  for root_file in "${SHARED_ROOT_FILES[@]}"; do
    [ -f "$TMP_ROOT/$root_file" ] || continue
    compare_file "$TMP_ROOT/$root_file" "$REPO_ROOT/$root_file" || errors=$((errors + 1))
  done

  compare_dir "$GENERATED_CLAUDE_DIR" "$TARGET_CLAUDE_DIR" || errors=$((errors + 1))
  compare_dir "$GENERATED_AGENTS_DIR" "$TARGET_AGENTS_DIR" || errors=$((errors + 1))

  if [ "$errors" -gt 0 ]; then
    exit 1
  fi

  echo "AI prompts and skills are in sync."
  exit 0
fi

if [ "$AGENT_FILES_WRITTEN" = true ]; then
  install_agent_files
fi

for root_file in "${SHARED_ROOT_FILES[@]}"; do
  [ -f "$TMP_ROOT/$root_file" ] || continue
  mkdir -p "$(dirname "$REPO_ROOT/$root_file")"
  cp "$TMP_ROOT/$root_file" "$REPO_ROOT/$root_file"
done

rm -rf "$TARGET_CLAUDE_DIR" "$TARGET_AGENTS_DIR"
mkdir -p "$TARGET_CLAUDE_DIR" "$TARGET_AGENTS_DIR"
cp -R "$GENERATED_CLAUDE_DIR/." "$TARGET_CLAUDE_DIR/"
cp -R "$GENERATED_AGENTS_DIR/." "$TARGET_AGENTS_DIR/"

echo "Synced AI prompts and skills into:"
if [ "$AGENT_FILES_WRITTEN" = true ]; then
  while IFS= read -r prompt_path; do
    [ -n "$prompt_path" ] && echo "  $REPO_ROOT/$prompt_path"
  done < "$GENERATED_PROMPT_REGISTRY"
fi
for root_file in "${SHARED_ROOT_FILES[@]}"; do
  [ -f "$TMP_ROOT/$root_file" ] && echo "  $REPO_ROOT/$root_file"
done
echo "  $TARGET_CLAUDE_DIR"
echo "  $TARGET_AGENTS_DIR"
