#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="${1:-.}"
REPO_ROOT="$(cd "$REPO_ROOT" && pwd)"

SHARED_ROOT="$REPO_ROOT/.ai/shared"
SHARED_SKILLS_DIR="$SHARED_ROOT/skills"
LOCAL_SKILLS_DIR="$REPO_ROOT/.ai/local-skills"

CLAUDE_DIR="$REPO_ROOT/.claude/commands"
AGENTS_DIR="$REPO_ROOT/.agents/skills"

strip_frontmatter() {
  local source_path="$1"

  awk '
    NR == 1 && $0 == "---" {
      in_frontmatter = 1
      next
    }
    in_frontmatter && $0 == "---" {
      in_frontmatter = 0
      next
    }
    !in_frontmatter {
      if (!started && $0 ~ /^[[:space:]]*$/) {
        next
      }
      started = 1
      print
    }
  ' "$source_path"
}

source_has_frontmatter() {
  local source_path="$1"

  head -n 1 "$source_path" | grep -qx -- "---"
}

derive_description() {
  local source_path="$1"

  strip_frontmatter "$source_path" | awk '
    /^# / && !seen_content {
      next
    }
    /^[[:space:]]*$/ {
      if (collecting) {
        exit
      }
      next
    }
    {
      line = $0
      gsub(/[[:space:]]+/, " ", line)
      if (!collecting) {
        description = line
        collecting = 1
        seen_content = 1
        next
      }
      description = description " " line
    }
    END {
      print description
    }
  '
}

yaml_quote() {
  local value="$1"

  value=${value//\'/\'\'}
  printf "'%s'" "$value"
}

copy_skill_to_claude() {
  local source_path="$1"
  local skill_name="$2"
  local target_dir="$3"

  strip_frontmatter "$source_path" > "$target_dir/$skill_name.md"
}

write_agent_skill() {
  local source_path="$1"
  local skill_name="$2"
  local target_path="$3"
  local description=""

  if source_has_frontmatter "$source_path"; then
    cp "$source_path" "$target_path"
    return
  fi

  description="$(derive_description "$source_path")"

  {
    printf -- '---\n'
    printf 'name: %s\n' "$skill_name"
    printf 'description: %s\n' "$(yaml_quote "$description")"
    printf -- '---\n\n'
    strip_frontmatter "$source_path"
  } > "$target_path"
}

copy_skill_to_agents() {
  local source_dir="$1"
  local entry="$2"
  local skill_name="$3"
  local target_dir="$4"
  local target_skill_dir="$target_dir/$skill_name"

  rm -rf "$target_skill_dir"
  mkdir -p "$target_skill_dir"

  if [ -d "$source_dir/$entry" ]; then
    cp -R "$source_dir/$entry/." "$target_skill_dir/"
    write_agent_skill "$source_dir/$entry/SKILL.md" "$skill_name" "$target_skill_dir/SKILL.md"
    return
  fi

  write_agent_skill "$source_dir/$entry" "$skill_name" "$target_skill_dir/SKILL.md"
}

sync_from_source() {
  local source_dir="$1"
  local claude_dir="$2"
  local agents_dir="$3"

  [ -d "$source_dir" ] || return 0

  find "$source_dir" -mindepth 1 -maxdepth 1 | sort | while read -r entry_path; do
    local entry skill_name source_skill_path
    entry="$(basename "$entry_path")"

    case "$entry" in
      .gitkeep|.DS_Store)
        continue
        ;;
    esac

    if [ -d "$entry_path" ]; then
      source_skill_path="$entry_path/SKILL.md"
      [ -f "$source_skill_path" ] || continue
      skill_name="$entry"
    else
      case "$entry" in
        *.md)
          skill_name="${entry%.md}"
          source_skill_path="$entry_path"
          ;;
        *)
          continue
          ;;
      esac
    fi

    copy_skill_to_claude "$source_skill_path" "$skill_name" "$claude_dir"
    copy_skill_to_agents "$source_dir" "$entry" "$skill_name" "$agents_dir"
  done
}

write_placeholder() {
  local target_dir="$1"

  cat > "$target_dir/.gitignore" <<'EOF'
# Generated by sync-ai-skills.sh.
# Keep this file so the directory exists even when no commands are synced yet.
EOF
}

rm -rf "$CLAUDE_DIR" "$AGENTS_DIR"
mkdir -p "$CLAUDE_DIR" "$AGENTS_DIR"

sync_from_source "$SHARED_SKILLS_DIR" "$CLAUDE_DIR" "$AGENTS_DIR"
sync_from_source "$LOCAL_SKILLS_DIR" "$CLAUDE_DIR" "$AGENTS_DIR"

write_placeholder "$CLAUDE_DIR"
write_placeholder "$AGENTS_DIR"

echo "Synced AI skills into:"
echo "  $CLAUDE_DIR"
echo "  $AGENTS_DIR"
